# Site wide configuration

title: Nerd Criativo
description: Desenvolvimento Web e Criatividade
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: pt
url: http://nerdcriativo.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: "Líverton Oliveira"
  email: lifelipe7@live.com
  twitter: lifelipe92
  google:
    ad-client: "ca-pub-8162405764064392"
    ad-slot: "4961143461"
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname: nerdcriativo

# Authors
data:
  authors:
    liverton:
      name: "Líverton Oliveira"
      bio: "Desenvolvedor de software e entusiasta de assuntos sobre criatividade"
      avatar: "media/compressed/bio-photo.jpg"
  navigation:
    - link:
      title: Feed
      url: atom.xml
    - link:
      title: Sobre
      url: /about

include: ["_pages"]
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
